# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vmware-system-csi

resources:
  - namespace.yaml
  - csi-vsphere-secret.yaml
  - vsphere-csi-driver.yaml

images:
  - name: registry.k8s.io/sig-storage/livenessprobe
    newName: registry.sighup.io/fury/vsphere/livenessprobe
  - name: registry.k8s.io/sig-storage/csi-attacher
    newName: registry.sighup.io/fury/vsphere/csi-attacher
  - name: registry.k8s.io/sig-storage/csi-snapshotter
    newName: registry.sighup.io/fury/vsphere/csi-snapshotter
  - name: registry.k8s.io/sig-storage/csi-resizer
    newName: registry.sighup.io/fury/vsphere/csi-resizer
  - name: registry.k8s.io/sig-storage/csi-provisioner
    newName: registry.sighup.io/fury/vsphere/csi-provisioner
  - name: registry.k8s.io/sig-storage/csi-node-driver-registrar
    newName: registry.sighup.io/fury/vsphere/csi-node-driver-registrar
  - name: registry.k8s.io/csi-vsphere/driver
    newName: registry.sighup.io/fury/csi-vsphere/syncer
  - name: registry.k8s.io/csi-vsphere/syncer
    newName: registry.sighup.io/fury/csi-vsphere/syncer
