apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vsphere-cloud-controller-manager.yaml

images:
  - name: registry.k8s.io/cloud-pv-vsphere/cloud-provider-vsphere
    newName: registry.sighup.io/fury/cloud-pv-vsphere/cloud-provider-vsphere
